### ISSUE TITLE
better highlight groups

### ISSUE THREAD

**Issue by max397574** [dgagn/diagflow.nvim#16]
There are standart highlight groups for lsp.
Not 100% sure but I think it's `LspDiagnostic*` (this also changed sometime in the past so I'm never completely sure)
I'm not at my computer with neovim rn so I can't check

I think it would make sense to just use this highlight groups instead of your own ones

**Comment by dgagn** [comment]
I appreciate your suggestion, and indeed I am utilizing the standard LSP highlight groups, as you can check in the documentation under `:h diagnostic-highlights`. These highlight groups are employed for coloring diagnostic messages in the diagnostics float.

I chose to use the diagnostics float because it's typically configured by default. An alternative could have been to use the `DiagnosticVirtualText...` groups, which might make more sense semantically. However, this would introduce a breaking change for anyone already using the UI, and I prefer to avoid that to maintain user experience continuity.

It's important to note that users do have the option to overwrite the groups by specifying their own `severity_colors` array, like so:

```
severity_colors = {  
    error = "DiagnosticFloatingError",
    warning = "DiagnosticFloatingWarn",
    info = "DiagnosticFloatingInfo",
    hint = "DiagnosticFloatingHint",
}
```

This allows for customization while also preserving the default behavior for those who prefer it.
